"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import {
  Alert,
  Badge,
  Button,
  EmptyState,
  PageHeader,
  Section,
  StatCard,
  StatusBadge,
  Table,
  Td,
  humanizeLabel,
} from "@nutrition-saas/ui";
import { api } from "../../../../lib/api";
import { errorMessage } from "../../../../lib/humanize-error";
import { Field, Input, Select, Textarea } from "@nutrition-saas/ui";

interface AutomationRule {
  id: string;
  name: string;
  status: string;
  triggerType: string;
  actionType: string;
  summary: string;
  lastRunAt: string | null;
}

interface UsageSummary {
  enabled: boolean;
  ruleLimit: number | null;
  activeRules: number;
  rulesRemaining: number | null;
  executionLimit: number | null;
  executionCount: number;
  executionsRemaining: number | null;
}

const TRIGGERS = [
  { value: "APPOINTMENT_UPCOMING", label: "Appointment is approaching", timingKey: "daysBefore", timingDefault: 1 },
  { value: "CLIENT_INACTIVE", label: "Client has no recent activity", timingKey: "daysInactive", timingDefault: 3 },
  { value: "INVOICE_OVERDUE", label: "Invoice is overdue", timingKey: null, timingDefault: null },
  { value: "TASK_DUE", label: "Task is due today", timingKey: null, timingDefault: null },
  { value: "MEAL_PLAN_ENDING", label: "Meal plan is ending soon", timingKey: "daysUntilEnd", timingDefault: 3 },
  { value: "CLIENT_CHECKIN_DUE", label: "Client check-in is due", timingKey: "intervalDays", timingDefault: 7 },
] as const;

const ACTIONS = [
  { value: "SEND_IN_APP_NOTIFICATION", label: "Send in-app notification" },
  { value: "SEND_EMAIL", label: "Send email" },
  { value: "CREATE_TASK", label: "Create follow-up task" },
  { value: "CREATE_CLIENT_NOTIFICATION", label: "Notify client (portal)" },
] as const;

const CLIENT_NAME_TOKEN = "{{client.displayName}}";
const CLIENT_NAME_FRIENDLY = "[Client name]";

function toFriendlyTemplate(value: string): string {
  return value.split(CLIENT_NAME_TOKEN).join(CLIENT_NAME_FRIENDLY);
}

function toApiTemplate(value: string): string {
  return value.split(CLIENT_NAME_FRIENDLY).join(CLIENT_NAME_TOKEN);
}

function triggerLabel(value: string): string {
  return TRIGGERS.find((t) => t.value === value)?.label ?? humanizeLabel(value);
}

function actionLabel(value: string): string {
  return ACTIONS.find((a) => a.value === value)?.label ?? humanizeLabel(value);
}

function humanRuleSummary(rule: AutomationRule): string {
  return `When ${triggerLabel(rule.triggerType).toLowerCase()} → ${actionLabel(rule.actionType).toLowerCase()}`;
}

export default function AutomationsPage() {
  const params = useParams<{ organizationId: string }>();
  const organizationId = params.organizationId;
  const [rules, setRules] = useState<AutomationRule[]>([]);
  const [usage, setUsage] = useState<UsageSummary | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showBuilder, setShowBuilder] = useState(false);
  const [saving, setSaving] = useState(false);

  const [name, setName] = useState("");
  const [triggerType, setTriggerType] = useState("CLIENT_INACTIVE");
  const [actionType, setActionType] = useState("CREATE_TASK");
  const [timingValue, setTimingValue] = useState(3);
  const [recipient, setRecipient] = useState("ASSIGNED_DIETITIAN");
  const [taskTitle, setTaskTitle] = useState(`Follow up with ${CLIENT_NAME_FRIENDLY}`);
  const [notificationTitle, setNotificationTitle] = useState("Automation reminder");
  const [notificationBody, setNotificationBody] = useState(
    `Review ${CLIENT_NAME_FRIENDLY} — generated by automation.`,
  );

  async function load() {
    const [ruleList, usageSummary] = await Promise.all([
      api<AutomationRule[]>(`/api/v1/organizations/${organizationId}/automations`),
      api<UsageSummary>(`/api/v1/organizations/${organizationId}/automations/usage/summary`),
    ]);
    setRules(ruleList);
    setUsage(usageSummary);
  }

  useEffect(() => {
    void load().catch((err) => setError(errorMessage(err, "Unable to load automations")));
  }, [organizationId]);

  const selectedTrigger = TRIGGERS.find((t) => t.value === triggerType);

  function buildConfiguration() {
    const timing: Record<string, number> = {};
    if (selectedTrigger?.timingKey) {
      timing[selectedTrigger.timingKey] = timingValue;
    }
    const configuration: Record<string, unknown> = {
      recipient,
      timing: Object.keys(timing).length ? timing : undefined,
    };
    if (actionType === "CREATE_TASK") {
      configuration.taskTitle = toApiTemplate(taskTitle);
      configuration.taskPriority = "HIGH";
    }
    if (actionType === "SEND_IN_APP_NOTIFICATION" || actionType === "CREATE_CLIENT_NOTIFICATION") {
      configuration.notificationTitle = toApiTemplate(notificationTitle);
      configuration.notificationBody = toApiTemplate(notificationBody);
    }
    if (actionType === "SEND_EMAIL") {
      configuration.emailSubject = toApiTemplate(notificationTitle);
      configuration.emailBody = toApiTemplate(notificationBody);
    }
    return configuration;
  }

  async function createRule(activate: boolean) {
    setSaving(true);
    try {
      const created = await api<AutomationRule>(`/api/v1/organizations/${organizationId}/automations`, {
        method: "POST",
        body: JSON.stringify({
          name: name || "New automation rule",
          triggerType,
          actionType,
          configuration: buildConfiguration(),
          conditions: triggerType === "CLIENT_INACTIVE" ? { clientStatus: "ACTIVE" } : undefined,
        }),
      });
      if (activate) {
        await api(`/api/v1/organizations/${organizationId}/automations/${created.id}/activate`, {
          method: "POST",
        });
      }
      setShowBuilder(false);
      setName("");
      await load();
    } catch (err) {
      setError(errorMessage(err, "Unable to create rule"));
    } finally {
      setSaving(false);
    }
  }

  async function setStatus(id: string, action: "activate" | "pause" | "archive") {
    try {
      await api(`/api/v1/organizations/${organizationId}/automations/${id}/${action}`, { method: "POST" });
      await load();
    } catch (err) {
      setError(errorMessage(err, "Unable to update rule"));
    }
  }

  const previewSummary = `When ${triggerLabel(triggerType).toLowerCase()} → ${actionLabel(actionType).toLowerCase()} to ${recipient.replace(/_/g, " ").toLowerCase()}`;

  return (
    <section>
      <PageHeader
        title="Automations"
        description="When something happens in the practice, trigger a task or reminder. You stay in control of every action."
        actions={
          <div className="ui-row">
            <Link href={`/practice/${organizationId}/automation-runs`} className="ui-btn ui-btn--secondary">
              Run history
            </Link>
            <Button onClick={() => setShowBuilder((v) => !v)}>
              {showBuilder ? "Close builder" : "Create rule"}
            </Button>
          </div>
        }
      />

      {error ? (
        <div style={{ marginBottom: 16 }}>
          <Alert tone="danger">{error}</Alert>
        </div>
      ) : null}

      {usage ? (
        <div className="ui-grid" style={{ marginBottom: 24 }}>
          <StatCard
            label="Feature status"
            value={usage.enabled ? "Enabled" : "Disabled"}
          />
          <StatCard
            label="Active rules"
            value={`${usage.activeRules}${usage.ruleLimit != null ? ` / ${usage.ruleLimit}` : ""}`}
            hint={usage.rulesRemaining != null ? `${usage.rulesRemaining} slots remaining` : undefined}
          />
          <StatCard
            label="Executions this month"
            value={`${usage.executionCount}${usage.executionLimit != null ? ` / ${usage.executionLimit}` : ""}`}
            hint={usage.executionsRemaining != null ? `${usage.executionsRemaining} remaining` : undefined}
          />
        </div>
      ) : null}

      {showBuilder ? (
        <Section
          title="Rule builder"
          description={previewSummary}
          tone="muted"
        >
          <div className="ui-rule-builder">
            <Field label="Rule name">
              <Input
                value={name}
                onChange={(e) => setName(e.target.value)}
                placeholder="Inactive client follow-up"
              />
            </Field>

            <div className="ui-rule-builder__steps">
              <div className="ui-rule-step">
                <p className="ui-rule-step__label">When</p>
                <Field label="Trigger">
                  <Select value={triggerType} onChange={(e) => setTriggerType(e.target.value)}>
                    {TRIGGERS.map((t) => (
                      <option key={t.value} value={t.value}>
                        {t.label}
                      </option>
                    ))}
                  </Select>
                </Field>
                {selectedTrigger?.timingKey ? (
                  <Field label="After how many days?">
                    <Input
                      type="number"
                      min={1}
                      value={timingValue}
                      onChange={(e) => setTimingValue(Number(e.target.value))}
                    />
                  </Field>
                ) : (
                  <p className="ui-muted" style={{ margin: 0, fontSize: 13 }}>
                    Runs as soon as this event happens.
                  </p>
                )}
              </div>

              <div className="ui-rule-step">
                <p className="ui-rule-step__label">Then</p>
                <Field label="Action">
                  <Select value={actionType} onChange={(e) => setActionType(e.target.value)}>
                    {ACTIONS.map((a) => (
                      <option key={a.value} value={a.value}>
                        {a.label}
                      </option>
                    ))}
                  </Select>
                </Field>
              </div>

              <div className="ui-rule-step">
                <p className="ui-rule-step__label">To</p>
                <Field label="Recipient">
                  <Select value={recipient} onChange={(e) => setRecipient(e.target.value)}>
                    <option value="ASSIGNED_DIETITIAN">Assigned dietitian</option>
                    <option value="RULE_CREATOR">Rule creator</option>
                    <option value="CLIENT">Client</option>
                  </Select>
                </Field>
              </div>
            </div>

            <div className="ui-rule-builder__details">
              {actionType === "CREATE_TASK" ? (
                <Field
                  label="Task title"
                  hint={`Use ${CLIENT_NAME_FRIENDLY} where the client's name should appear.`}
                >
                  <Input
                    value={toFriendlyTemplate(taskTitle)}
                    onChange={(e) => setTaskTitle(toFriendlyTemplate(e.target.value))}
                    placeholder={`Follow up with ${CLIENT_NAME_FRIENDLY}`}
                  />
                  <div className="ui-token-chip">
                    <button
                      type="button"
                      onClick={() =>
                        setTaskTitle((current) =>
                          current.includes(CLIENT_NAME_FRIENDLY)
                            ? current
                            : `${current.trim()} ${CLIENT_NAME_FRIENDLY}`.trim(),
                        )
                      }
                    >
                      Insert client name
                    </button>
                  </div>
                </Field>
              ) : (
                <>
                  <Field label="Title / subject">
                    <Input
                      value={toFriendlyTemplate(notificationTitle)}
                      onChange={(e) => setNotificationTitle(toFriendlyTemplate(e.target.value))}
                    />
                  </Field>
                  <Field
                    label="Message"
                    hint={`Use ${CLIENT_NAME_FRIENDLY} to insert the client's name automatically.`}
                  >
                    <Textarea
                      value={toFriendlyTemplate(notificationBody)}
                      onChange={(e) => setNotificationBody(toFriendlyTemplate(e.target.value))}
                      style={{ minHeight: 80 }}
                    />
                    <div className="ui-token-chip">
                      <button
                        type="button"
                        onClick={() =>
                          setNotificationBody((current) =>
                            current.includes(CLIENT_NAME_FRIENDLY)
                              ? current
                              : `${current.trim()} ${CLIENT_NAME_FRIENDLY}`.trim(),
                          )
                        }
                      >
                        Insert client name
                      </button>
                    </div>
                  </Field>
                </>
              )}
            </div>

            <div className="ui-row">
              <Button disabled={saving} variant="secondary" onClick={() => void createRule(false)}>
                {saving ? "Saving…" : "Save as paused"}
              </Button>
              <Button disabled={saving} onClick={() => void createRule(true)}>
                {saving ? "Saving…" : "Save & activate"}
              </Button>
            </div>
          </div>
        </Section>
      ) : null}

      <Section title="Rules">
        {rules.length === 0 ? (
          <EmptyState
            title="No automation rules yet"
            action={
              <Button onClick={() => setShowBuilder(true)}>Create your first rule</Button>
            }
          >
            Use the rule builder to trigger tasks or reminders when something happens in the practice.
          </EmptyState>
        ) : (
          <Table>
            <thead>
              <tr>
                <th>Name</th>
                <th>Status</th>
                <th>Rule</th>
                <th>Last run</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {rules.map((rule) => (
                <tr key={rule.id}>
                  <Td label="Name">
                    <Link href={`/practice/${organizationId}/automations/${rule.id}`} className="ui-link">
                      {rule.name}
                    </Link>
                  </Td>
                  <Td label="Status">
                    <StatusBadge status={rule.status} label={humanizeLabel(rule.status)} />
                  </Td>
                  <Td label="Rule">
                    <span className="ui-muted" style={{ fontSize: "0.875rem" }}>
                      {humanRuleSummary(rule)}
                    </span>
                  </Td>
                  <Td label="Last run">
                    {rule.lastRunAt ? (
                      <time dateTime={rule.lastRunAt}>{new Date(rule.lastRunAt).toLocaleDateString()}</time>
                    ) : (
                      <span className="ui-muted">Never</span>
                    )}
                  </Td>
                  <Td label="Actions">
                    <div className="ui-row">
                      {rule.status !== "ACTIVE" ? (
                        <button
                          type="button"
                          className="ui-btn ui-btn--secondary ui-btn--sm"
                          onClick={() => void setStatus(rule.id, "activate")}
                        >
                          Activate
                        </button>
                      ) : (
                        <button
                          type="button"
                          className="ui-btn ui-btn--secondary ui-btn--sm"
                          onClick={() => void setStatus(rule.id, "pause")}
                        >
                          Pause
                        </button>
                      )}
                      {rule.status !== "ARCHIVED" ? (
                        <button
                          type="button"
                          className="ui-btn ui-btn--ghost ui-btn--sm"
                          onClick={() => void setStatus(rule.id, "archive")}
                        >
                          Archive
                        </button>
                      ) : null}
                    </div>
                  </Td>
                </tr>
              ))}
            </tbody>
          </Table>
        )}
      </Section>

      {rules.length > 0 ? (
        <p style={{ fontSize: "0.8125rem", marginTop: 8 }} className="ui-muted">
          <Badge tone="neutral">{rules.filter((r) => r.status === "ACTIVE").length} active</Badge>{" "}
          <Badge tone="neutral">{rules.filter((r) => r.status === "PAUSED").length} paused</Badge>
        </p>
      ) : null}
    </section>
  );
}
