-- Expand clinical measurement catalog (body composition, skinfolds, analytical).
ALTER TYPE "MeasurementType" ADD VALUE 'FAT_MASS';
ALTER TYPE "MeasurementType" ADD VALUE 'MUSCLE_MASS_PERCENT';
ALTER TYPE "MeasurementType" ADD VALUE 'SKINFOLD_ABDOMINAL';
ALTER TYPE "MeasurementType" ADD VALUE 'SKINFOLD_CHEST';
ALTER TYPE "MeasurementType" ADD VALUE 'SKINFOLD_FRONT_THIGH';
ALTER TYPE "MeasurementType" ADD VALUE 'SKINFOLD_MIDAXILLARY';
ALTER TYPE "MeasurementType" ADD VALUE 'SKINFOLD_SUBSCAPULAR';
ALTER TYPE "MeasurementType" ADD VALUE 'SKINFOLD_SUPRAILIAC';
ALTER TYPE "MeasurementType" ADD VALUE 'SKINFOLD_TRICEPS';
ALTER TYPE "MeasurementType" ADD VALUE 'BP_DIASTOLIC';
ALTER TYPE "MeasurementType" ADD VALUE 'BP_SYSTOLIC';
ALTER TYPE "MeasurementType" ADD VALUE 'CHOLESTEROL_HDL';
ALTER TYPE "MeasurementType" ADD VALUE 'CHOLESTEROL_LDL';
ALTER TYPE "MeasurementType" ADD VALUE 'CHOLESTEROL_TOTAL';
ALTER TYPE "MeasurementType" ADD VALUE 'TRIGLYCERIDES';
