import { z } from "zod";

export { z };

export const envSchema = z.object({
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  LOG_LEVEL: z.string().default("info"),
  API_PORT: z.coerce.number().int().positive().default(3001),
  DATABASE_URL: z.string().min(1),
  REDIS_URL: z.string().min(1),
  FILE_STORAGE_PATH: z.string().min(1),
  CORS_ORIGIN: z.string().default("http://localhost:3000"),
  SWAGGER_ENABLED: z.string().optional(),
  APP_URL: z.string().default("http://localhost:3000"),
  AUTH_TOKEN_SECRET: z.string().min(32),
  SESSION_TTL_SECONDS: z.coerce.number().int().positive().default(60 * 60 * 24 * 7),
  EMAIL_VERIFICATION_TTL_SECONDS: z.coerce.number().int().positive().default(60 * 60 * 24),
  PASSWORD_RESET_TTL_SECONDS: z.coerce.number().int().positive().default(60 * 60),
  INVITATION_TTL_SECONDS: z.coerce.number().int().positive().default(60 * 60 * 24 * 7),
  PASSWORD_MIN_LENGTH: z.coerce.number().int().min(8).default(10),
  AUTH_THROTTLE_TTL_MS: z.coerce.number().int().positive().default(60_000),
  AUTH_THROTTLE_LIMIT: z.coerce.number().int().positive().default(10),
  MAX_DOCUMENT_BYTES: z.coerce.number().int().positive().default(20 * 1024 * 1024),
  COOKIE_SECURE: z.string().optional(),
  AI_ENABLED: z.string().optional(),
  AI_PROVIDER: z.enum(["mock", "openai"]).default("mock"),
  AI_API_KEY: z.string().optional(),
  AI_MODEL: z.string().default("gpt-4o-mini"),
  AI_BASE_URL: z.string().optional(),
  AI_TIMEOUT_MS: z.coerce.number().int().positive().default(30_000),
  AI_MAX_INPUT_TOKENS: z.coerce.number().int().positive().default(8_000),
  AI_MAX_OUTPUT_TOKENS: z.coerce.number().int().positive().default(2_000),
  EMAIL_PROVIDER: z.enum(["console", "smtp"]).default("console"),
  EMAIL_FROM: z.string().optional(),
  SMTP_HOST: z.string().optional(),
  SMTP_PORT: z.coerce.number().int().positive().optional(),
  SMTP_USER: z.string().optional(),
  SMTP_PASSWORD: z.string().optional(),
  SMTP_SECURE: z.string().optional(),
  MESSAGING_THROTTLE_TTL_MS: z.coerce.number().int().positive().default(60_000),
  MESSAGING_THROTTLE_LIMIT: z.coerce.number().int().positive().default(30),
  UPLOAD_THROTTLE_TTL_MS: z.coerce.number().int().positive().default(60_000),
  UPLOAD_THROTTLE_LIMIT: z.coerce.number().int().positive().default(20),
  AI_THROTTLE_TTL_MS: z.coerce.number().int().positive().default(60_000),
  AI_THROTTLE_LIMIT: z.coerce.number().int().positive().default(20),
  ERROR_TRACKING_ENABLED: z.string().optional(),
});

export type AppEnv = z.infer<typeof envSchema>;
