-- Patient cancellation requests require dietitian approval.
ALTER TYPE "AppointmentStatus" ADD VALUE IF NOT EXISTS 'CANCELLATION_PENDING';

ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_CANCELLATION_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_CANCELLATION_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'APPOINTMENT_CANCELLATION_REJECTED';
