"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { api } from "../../../../lib/api";
import { humanizeLabel } from "@nutrition-saas/ui";
interface AutomationRule {
  id: string;
  name: string;
  status: string;
  triggerType: string;
  actionType: string;
  summary: string;
  lastRunAt: string | null;
}

interface UsageSummary {
  enabled: boolean;
  ruleLimit: number | null;
  activeRules: number;
  rulesRemaining: number | null;
  executionLimit: number | null;
  executionCount: number;
  executionsRemaining: number | null;
}

const TRIGGERS = [
  { value: "APPOINTMENT_UPCOMING", label: "Appointment is approaching", timingKey: "daysBefore", timingDefault: 1 },
  { value: "CLIENT_INACTIVE", label: "Client has no recent activity", timingKey: "daysInactive", timingDefault: 3 },
  { value: "INVOICE_OVERDUE", label: "Invoice is overdue", timingKey: null, timingDefault: null },
  { value: "TASK_DUE", label: "Task is due today", timingKey: null, timingDefault: null },
  { value: "MEAL_PLAN_ENDING", label: "Meal plan is ending soon", timingKey: "daysUntilEnd", timingDefault: 3 },
  { value: "CLIENT_CHECKIN_DUE", label: "Client check-in is due", timingKey: "intervalDays", timingDefault: 7 },
] as const;

const ACTIONS = [
  { value: "SEND_IN_APP_NOTIFICATION", label: "Send in-app notification" },
  { value: "SEND_EMAIL", label: "Send email" },
  { value: "CREATE_TASK", label: "Create follow-up task" },
  { value: "CREATE_CLIENT_NOTIFICATION", label: "Notify client (portal)" },
] as const;

export default function AutomationsPage() {
  const params = useParams<{ organizationId: string }>();
  const organizationId = params.organizationId;
  const [rules, setRules] = useState<AutomationRule[]>([]);
  const [usage, setUsage] = useState<UsageSummary | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [showBuilder, setShowBuilder] = useState(false);

  const [name, setName] = useState("");
  const [triggerType, setTriggerType] = useState("CLIENT_INACTIVE");
  const [actionType, setActionType] = useState("CREATE_TASK");
  const [timingValue, setTimingValue] = useState(3);
  const [recipient, setRecipient] = useState("ASSIGNED_DIETITIAN");
  const [taskTitle, setTaskTitle] = useState("Follow up with {{client.displayName}}");
  const [notificationTitle, setNotificationTitle] = useState("Automation reminder");
  const [notificationBody, setNotificationBody] = useState(
    "Review {{client.displayName}} — generated by automation.",
  );

  async function load() {
    const [ruleList, usageSummary] = await Promise.all([
      api<AutomationRule[]>(`/api/v1/organizations/${organizationId}/automations`),
      api<UsageSummary>(`/api/v1/organizations/${organizationId}/automations/usage/summary`),
    ]);
    setRules(ruleList);
    setUsage(usageSummary);
  }

  useEffect(() => {
    void load().catch((err) => setError(err instanceof Error ? err.message : "Unable to load automations"));
  }, [organizationId]);

  const selectedTrigger = TRIGGERS.find((t) => t.value === triggerType);

  function buildConfiguration() {
    const timing: Record<string, number> = {};
    if (selectedTrigger?.timingKey) {
      timing[selectedTrigger.timingKey] = timingValue;
    }
    const configuration: Record<string, unknown> = {
      recipient,
      timing: Object.keys(timing).length ? timing : undefined,
    };
    if (actionType === "CREATE_TASK") {
      configuration.taskTitle = taskTitle;
      configuration.taskPriority = "HIGH";
    }
    if (actionType === "SEND_IN_APP_NOTIFICATION" || actionType === "CREATE_CLIENT_NOTIFICATION") {
      configuration.notificationTitle = notificationTitle;
      configuration.notificationBody = notificationBody;
    }
    if (actionType === "SEND_EMAIL") {
      configuration.emailSubject = notificationTitle;
      configuration.emailBody = notificationBody;
    }
    return configuration;
  }

  async function createRule(activate: boolean) {
    const created = await api<AutomationRule>(`/api/v1/organizations/${organizationId}/automations`, {
      method: "POST",
      body: JSON.stringify({
        name: name || "New automation rule",
        triggerType,
        actionType,
        configuration: buildConfiguration(),
        conditions: triggerType === "CLIENT_INACTIVE" ? { clientStatus: "ACTIVE" } : undefined,
      }),
    });
    if (activate) {
      await api(`/api/v1/organizations/${organizationId}/automations/${created.id}/activate`, {
        method: "POST",
      });
    }
    setShowBuilder(false);
    setName("");
    await load();
  }

  async function setStatus(id: string, action: "activate" | "pause" | "archive") {
    await api(`/api/v1/organizations/${organizationId}/automations/${id}/${action}`, { method: "POST" });
    await load();
  }

  if (error) {
    return (
      <main>
        <p>{error}</p>
      </main>
    );
  }

  return (
    <div>
      <h1 style={{ marginTop: 0 }}>Automations</h1>
      <p className="ui-muted">
        When something happens in the practice, then create a task or send a reminder. You stay in control of every action.
      </p>

      {usage ? (
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))",
            gap: 12,
            marginBottom: 20,
          }}
        >
          <Stat label="Enabled" value={usage.enabled ? "Yes" : "No"} />
          <Stat label="Active rules" value={`${usage.activeRules}${usage.ruleLimit != null ? ` / ${usage.ruleLimit}` : ""}`} />
          <Stat
            label="Executions (month)"
            value={`${usage.executionCount}${usage.executionLimit != null ? ` / ${usage.executionLimit}` : ""}`}
          />
        </div>
      ) : null}

      <div style={{ marginBottom: 16, display: "flex", gap: 8 }}>
        <button type="button" className="ui-btn ui-btn--primary" onClick={() => setShowBuilder((v) => !v)}>
          {showBuilder ? "Close builder" : "Create rule"}
        </button>
        <Link href={`/orgs/${organizationId}/automation-runs`} style={{ alignSelf: "center", color: "var(--color-accent)" }}>
          View run history
        </Link>
      </div>

      {showBuilder ? (
        <section
          style={{
            background: "var(--color-surface)",
            border: "1px solid var(--color-border)",
            borderRadius: 12,
            padding: 16,
            marginBottom: 24,
          }}
        >
          <h2 style={{ marginTop: 0, fontSize: 18 }}>Rule builder</h2>
          <label className="ui-field">
            Name
            <input className="ui-input" value={name} onChange={(e) => setName(e.target.value)} placeholder="Inactive client follow-up" />
          </label>
          <label className="ui-field">
            When
            <select className="ui-input" value={triggerType} onChange={(e) => setTriggerType(e.target.value)}>
              {TRIGGERS.map((t) => (
                <option key={t.value} value={t.value}>
                  {t.label}
                </option>
              ))}
            </select>
          </label>
          {selectedTrigger?.timingKey ? (
            <label className="ui-field">
              After how many days?
              <input
                className="ui-input"
                type="number"
                min={1}
                value={timingValue}
                onChange={(e) => setTimingValue(Number(e.target.value))}
              />
            </label>
          ) : null}
          <label className="ui-field">
            Then
            <select className="ui-input" value={actionType} onChange={(e) => setActionType(e.target.value)}>
              {ACTIONS.map((a) => (
                <option key={a.value} value={a.value}>
                  {a.label}
                </option>
              ))}
            </select>
          </label>
          <label className="ui-field">
            Recipient
            <select className="ui-input" value={recipient} onChange={(e) => setRecipient(e.target.value)}>
              <option value="ASSIGNED_DIETITIAN">Assigned dietitian</option>
              <option value="RULE_CREATOR">Rule creator</option>
              <option value="CLIENT">Client</option>
            </select>
          </label>
          {actionType === "CREATE_TASK" ? (
            <label className="ui-field">
              Task title
              <input className="ui-input" value={taskTitle} onChange={(e) => setTaskTitle(e.target.value)} />
            </label>
          ) : null}
          {actionType !== "CREATE_TASK" ? (
            <>
              <label className="ui-field">
                Title / subject
                <input className="ui-input" value={notificationTitle} onChange={(e) => setNotificationTitle(e.target.value)} />
              </label>
              <label className="ui-field">
                Body
                <textarea
                  className="ui-input" style={{minHeight: 80}}
                  value={notificationBody}
                  onChange={(e) => setNotificationBody(e.target.value)}
                />
              </label>
            </>
          ) : null}
          <p style={{ fontSize: 13, color: "var(--color-muted)" }}>
            Summary: When {selectedTrigger?.label.toLowerCase()}, then{" "}
            {ACTIONS.find((a) => a.value === actionType)?.label.toLowerCase()} to {recipient.replace(/_/g, " ").toLowerCase()}.
          </p>
          <div style={{ display: "flex", gap: 8 }}>
            <button type="button" className="ui-btn ui-btn--primary" onClick={() => void createRule(false).catch((e) => setError(String(e)))}>
              Save as paused
            </button>
            <button type="button" className="ui-btn ui-btn--primary" onClick={() => void createRule(true).catch((e) => setError(String(e)))}>
              Activate
            </button>
          </div>
        </section>
      ) : null}

      <table className="ui-table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Status</th>
            <th>Summary</th>
            <th>Last run</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {rules.map((rule) => (
            <tr key={rule.id}>
              <td>
                <Link href={`/orgs/${organizationId}/automations/${rule.id}`} style={{ color: "var(--color-accent)" }}>
                  {rule.name}
                </Link>
              </td>
              <td>{humanizeLabel(rule.status)}</td>
              <td>{rule.summary}</td>
              <td>{rule.lastRunAt ? new Date(rule.lastRunAt).toLocaleString() : "—"}</td>
              <td>
                {rule.status !== "ACTIVE" ? (
                  <button type="button" className="ui-btn ui-btn--primary" onClick={() => void setStatus(rule.id, "activate")}>
                    Activate
                  </button>
                ) : (
                  <button type="button" className="ui-btn ui-btn--primary" onClick={() => void setStatus(rule.id, "pause")}>
                    Pause
                  </button>
                )}{" "}
                {rule.status !== "ARCHIVED" ? (
                  <button type="button" className="ui-btn ui-btn--primary" onClick={() => void setStatus(rule.id, "archive")}>
                    Archive
                  </button>
                ) : null}
              </td>
            </tr>
          ))}
        </tbody>
      </table>
      {rules.length === 0 ? <p>No automation rules yet.</p> : null}
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ background: "var(--color-surface)", border: "1px solid var(--color-border)", borderRadius: 8, padding: 12 }}>
      <p style={{ margin: 0, fontSize: 12, color: "var(--color-muted)" }}>{label}</p>
      <p style={{ margin: "4px 0 0", fontWeight: 600 }}>{value}</p>
    </div>
  );
}
